filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/ossec/logs/alerts/alerts.json  

output.elasticsearch:
  hosts: ["http://<ELASTICSEARCH_IP>:9200"]  
  index: "wazuh-alerts-%{+yyyy.MM.dd}"     
